# Generated by Django 4.2.29 on 2026-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_wallet', models.CharField(max_length=44)),
                ('file_name', models.CharField(max_length=255)),
                ('encrypted_file', models.FileField(upload_to='secure_blobs/')),
                ('required_nft_address', models.CharField(max_length=4)),
            ],
        ),
    ]
