# Generated by Django 4.2.29 on 2026-03-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_encrypteddocument_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encrypteddocument',
            name='required_nft_address',
            field=models.CharField(max_length=44),
        ),
    ]
